name:                monadic-parsing
version:             0.1.0.0
author:              "Monisha Vatikuti"
maintainer:          "mav12@illinois.edu"
copyright:           "2022 Monisha Vatikuti"

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  monadic-pearl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-parsing

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-parsing
    - QuickCheck
    - HUnit >= 1.5
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-io

